name: train_vision
description: Train AutoML Vision model for crop analysis

inputs:
- {name: project_id, type: String, description: 'GCP project ID'}
- {name: region, type: String, description: 'GCP region'}
- {name: dataset, type: String, description: 'URI of the processed vision dataset'}
- {name: min_accuracy, type: Float, description: 'Minimum required accuracy'}

outputs:
- {name: model_info, type: Dict, description: 'Model information including resource name and metrics'}

implementation:
  container:
    image: python:3.9
    command:
    - sh
    - -c
    - |
      python3 -m pip install --no-cache-dir \
        google-cloud-aiplatform==1.25.0 \
        google-cloud-storage==2.9.0 \
        protobuf<4.0.0dev \
        pydantic<3.0.0
      python3 -c
    - |
      import os
      import sys
      import argparse
      from google.cloud import aiplatform
      import json

      # Parse command line arguments
      parser = argparse.ArgumentParser()
      parser.add_argument('--project_id', type=str, required=True)
      parser.add_argument('--region', type=str, required=True)
      parser.add_argument('--dataset', type=str, required=True)
      parser.add_argument('--min_accuracy', type=float, required=True)
      args = parser.parse_args()

      # Initialize Vertex AI
      aiplatform.init(project=args.project_id, location=args.region)

      # Create dataset
      ai_dataset = aiplatform.ImageDataset.create(
          display_name="crop_vision_dataset",
          gcs_source=args.dataset
      )

      # Train model
      job = aiplatform.AutoMLImageTrainingJob(
          display_name="crop_vision_model",
          prediction_type="classification",
          budget_milli_node_hours=83,  # Approximately 5 minutes (83 milli-node hours)
          model_type="CLOUD",
          base_model=None
      )

      # Run the training job
      ai_model = job.run(
          dataset=ai_dataset,
          budget_milli_node_hours=83,  # 5 minutes for testing
          training_filter_split="",  # No filter
          model_display_name="crop_vision_model",
          training_fraction_split=0.8,
          validation_fraction_split=0.1,
          test_fraction_split=0.1
      )

      # Get model evaluation
      eval_metrics = ai_model.list_model_evaluations()[0]

      # Check if model meets accuracy threshold
      if eval_metrics.metrics['auRoc'] < args.min_accuracy:
          raise ValueError(f"Model accuracy {eval_metrics.metrics['auRoc']} below threshold {args.min_accuracy}")

      # Print output as JSON for KFP
      model_info = {
          'model': ai_model.resource_name,
          'accuracy': float(eval_metrics.metrics['auRoc'])
      }
      print(json.dumps(model_info))
    args:
    - --project_id
    - {inputValue: project_id}
    - --region
    - {inputValue: region}
    - --dataset
    - {inputValue: dataset}
    - --min_accuracy
    - {inputValue: min_accuracy}
