name: train_tabular
description: Train AutoML Tabular model for crop yield prediction

inputs:
- {name: project_id, type: String, description: 'GCP project ID'}
- {name: region, type: String, description: 'GCP region'}
- {name: dataset, type: String, description: 'URI of the processed tabular dataset'}
- {name: min_accuracy, type: Float, description: 'Minimum required accuracy'}

outputs:
- {name: model_info, type: Dict, description: 'Model information including resource name and metrics'}

implementation:
  container:
    image: python:3.9
    command:
    - sh
    - -c
    - |
      python3 -m pip install --quiet google-cloud-aiplatform pandas numpy
      python3 -c
    - |
      import sys
      import argparse
      from google.cloud import aiplatform

      parser = argparse.ArgumentParser()
      parser.add_argument('--project_id')
      parser.add_argument('--region')
      parser.add_argument('--dataset')
      parser.add_argument('--min_accuracy', type=float)
      args = parser.parse_args()

      # Initialize Vertex AI
      aiplatform.init(project=args.project_id, location=args.region)

      # Create dataset
      ai_dataset = aiplatform.TabularDataset.create(
          display_name="crop_tabular_dataset",
          gcs_source=args.dataset
      )

      # Train model
      job = aiplatform.AutoMLTabularTrainingJob(
          display_name="crop_tabular_model",
          optimization_prediction_type="regression",
          optimization_objective="minimize-rmse"
      )

      ai_model = job.run(
          dataset=ai_dataset,
          target_column="yield",
          budget_milli_node_hours=83.33,  # 5 minutes
          model_display_name="crop_tabular_model",
          training_fraction_split=0.8,
          validation_fraction_split=0.1,
          test_fraction_split=0.1
      )

      # Evaluate model
      eval_metrics = ai_model.get_model_evaluation()
      if eval_metrics.metrics['rmse'] > args.min_accuracy:
          raise ValueError(f"Model RMSE {eval_metrics.metrics['rmse']} above threshold {args.min_accuracy}")

      # Print output as JSON for KFP
      import json
      model_info = {
          'model': ai_model.resource_name,
          'rmse': float(eval_metrics.metrics['rmse'])
      }
      print(json.dumps(model_info))
    args:
    - --project_id
    - {inputValue: project_id}
    - --region
    - {inputValue: region}
    - --dataset
    - {inputValue: dataset}
    - --min_accuracy
    - {inputValue: min_accuracy}
